# [build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  # cache Cypress binary in local "node_modules" folder
  # so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    record = true
    group = 'deployed'
    spec = "cypress/integration/smoke/**/*.js"
  # run Cypress tests before building and deploying
  [plugins.inputs.preBuild]
    enable = true
    # call the same commands as we do locally
    start = 'yarn start'
    wait-on = 'http://localhost:3000'
    record = true
    group = 'before deploy'
    tag = 'netlify'
